baseURL = "https://untoldwind.github.io/KontrolSystem/"
languageCode = "en-us"
title = "KontrolSystem"

theme = "hugo-theme-learn"

publishDir = "../docs"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "to2"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1